# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 231bcfdb69f2bd0f0f109055a1f1d7ad6f1e67c7fa666dda058856bb68c30b75bdd550a7a71d70f49872c8b8a4032133635273a756e84c4be084416ea6f31c1d

test:
  secret_key_base: fa61ffbdaf985b1345e9b9fba509390ff248cc57cc32f54474a277bc0445c2890a422de85c8b2bd5885cd620f8bd7f87024b53967855afe80f2d1ecdad5402ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
